development
  # Configure available database sessions. (required)
  sessions
    # Defines the default session. (required)
    default
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database something
      # Provides the hosts the default session can connect to. Must be an array
      # of hostport pairs. (required)
      hosts
        - localhost27017